api template added
acikkaynak/depremadres-intent-classification-v0 pull request #16
Opened 2023-02-08 23:06 UTC by yunusemreemik

2023-02-08 23:32 UTC, ybgirgin3 commented
dizin içinde oluşturduğun virtual environment'ını gitignore'a eklememişsin sanırım. değişiklik yapılan dosyaların sayısı 5000+ fazla gözüküyor.

2023-02-08 23:35 UTC, ybgirgin3 requested changes
proje ile aynı dizindeki virtual environmentini .gitignore'a eklemelisin. 5000+ dosya yüklenmiş. gerekli paketlerin yüklenmesi için yapılmasını istiyorsak eğer (pip için) requirements.txt ya da (conda için) environment.yml daha efektif bir yöntem olacaktır

2023-02-08 23:38 UTC, EralpKocas requested changes
.gitignore'u duzenleyip venv altindaki dosyalari kaldirabilir misin? tesekkur ederim.

2023-02-09 07:35 UTC, ozkanuysal commented
Eğer önerilen işlemleri yaptıysanız pr'ı closed durumuna getirebilir misiniz.Teşekkürler

2023-02-09 11:45 UTC, yunusemreemik commented
Selamlar dün gece yoğun migren ağrısından dolayı yarım bırakıp çıktım. Kusura bakmayınız düzenleyip güncelleyeceğim.

2023-02-09 12:22 UTC, closed without merging